# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_remove_comments_pm'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleAccountLiked',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articleaccountliked_header', to='mainApp.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articleaccountliked_user', to='mainApp.Account')),
            ],
        ),
    ]
