# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 03:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20171210_0329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pm', models.BooleanField(default=True)),
                ('time', models.DateTimeField()),
                ('text', models.CharField(max_length=4096)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_header', to='mainApp.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_user', to='mainApp.Account')),
            ],
        ),
    ]
